const cardsFamily = [
  {
    id: 49,
    word: 'grandfather',
    translation: 'дедушка',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/grandfather.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/grandfather.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 50,
    word: 'children',
    translation: 'дети',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/children.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/children.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 51,
    word: 'dad',
    translation: 'папа',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/dad.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/dad.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 52,
    word: 'grandmother',
    translation: 'бабушка',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/grandmother.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/grandmother.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 53,
    word: 'mother',
    translation: 'мама',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/mother.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/mother.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 54,
    word: 'relative',
    translation: 'родственник',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/relative.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/relative.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 55,
    word: 'grandparent',
    translation: 'дедушка, бабушка',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/grandparent.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/grandparent.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 56,
    word: 'baby',
    translation: 'малыш',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/baby.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/baby.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsFamily;
