const cardsAnimalA = [
  {
    id: 17,
    word: 'cat',
    translation: 'кот',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/cat.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/cat.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 18,
    word: 'chick',
    translation: 'цыплёнок',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/chick.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/chick.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 19,
    word: 'chicken',
    translation: 'курица',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/chicken.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/chicken.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 20,
    word: 'dog',
    translation: 'собака',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/dog.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/dog.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 21,
    word: 'horse',
    translation: 'лошадь',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/horse.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/horse.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 22,
    word: 'pig',
    translation: 'свинья',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/pig.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/pig.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 23,
    word: 'rabbit',
    translation: 'кролик',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/rabbit.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/rabbit.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 24,
    word: 'sheep',
    translation: 'овца',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/sheep.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/sheep.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsAnimalA;
