const cardsEmotions = [
  {
    id: 41,
    word: 'sad',
    translation: 'грустный',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/sad.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/sad.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 42,
    word: 'angry',
    translation: 'сердитый',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/angry.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/angry.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 43,
    word: 'happy',
    translation: 'счастливый',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/happy.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/happy.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 44,
    word: 'tired',
    translation: 'уставший',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/tired.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/tired.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 45,
    word: 'surprised',
    translation: 'удивлённый',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/surprised.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/surprised.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 46,
    word: 'scared',
    translation: 'испуганный',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/scared.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/scared.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 47,
    word: 'smile',
    translation: 'улыбка',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/smile.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/smile.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 48,
    word: 'laugh',
    translation: 'смех',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/laugh.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/laugh.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsEmotions;
