const cardsFood = [
  {
    id: 57,
    word: 'cucumber',
    translation: 'огурец',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/cucumber.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/cucumber.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 58,
    word: 'strawberry',
    translation: 'клубника',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/strawberry.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/strawberry.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 59,
    word: 'bread',
    translation: 'хлеб',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/bread.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/bread.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 60,
    word: 'carrot',
    translation: 'морковь',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/carrot.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/carrot.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 61,
    word: 'cheese',
    translation: 'сыр',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/cheese.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/cheese.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 62,
    word: 'meat',
    translation: 'мясо',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/meat.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/meat.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 63,
    word: 'tomato',
    translation: 'помидор',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/tomato.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/tomato.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 64,
    word: 'banana',
    translation: 'банан',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/banana.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/banana.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsFood;
