const cardsSetB = [
  {
    id: 9,
    word: 'open',
    translation: 'открывать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/open.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/open.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 10,
    word: 'play',
    translation: 'играть',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/play.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/play.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 11,
    word: 'point',
    translation: 'указывать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/point.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/point.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 12,
    word: 'ride',
    translation: 'ездить',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/ride.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/ride.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 13,
    word: 'run',
    translation: 'бегать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/run.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/run.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 14,
    word: 'sing',
    translation: 'петь',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/sing.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/sing.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 15,
    word: 'skip',
    translation: 'прыгать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/skip.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/skip.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 16,
    word: 'swim',
    translation: 'плавать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/swim.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/swim.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsSetB;
