const cardsSetA = [
  {
    id: 1,
    word: 'cry',
    translation: 'плакать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/cry.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/cry.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 2,
    word: 'dance',
    translation: 'танцевать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/dance.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/dance.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 3,
    word: 'dive',
    translation: 'нырять',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/dive.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/dive.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 4,
    word: 'draw',
    translation: 'рисовать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/draw.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/draw.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 5,
    word: 'build',
    translation: 'строить',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/build.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/build.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 6,
    word: 'fly',
    translation: 'летать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/fly.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/fly.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 7,
    word: 'hug',
    translation: 'обнимать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/hug.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/hug.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 8,
    word: 'jump',
    translation: 'прыгать',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/jump.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/jump.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsSetA;
