const cardsAnimalB = [
  {
    id: 25,
    word: 'bird',
    translation: 'птица',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/bird.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/bird.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 26,
    word: 'fish',
    translation: 'рыба',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/fish.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/fish.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 27,
    word: 'frog',
    translation: 'жаба',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/frog.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/frog.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 28,
    word: 'giraffe',
    translation: 'жираф',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/giraffe.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/giraffe.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 29,
    word: 'lion',
    translation: 'лев',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/lion.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/lion.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 30,
    word: 'mouse',
    translation: 'мышь',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/mouse.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/mouse.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 31,
    word: 'turtle',
    translation: 'черепаха',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/turtle.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/turtle.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 32,
    word: 'dolphin',
    translation: 'дельфин',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/dolphin.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/dolphin.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsAnimalB;
