const cardsClothes = [
  {
    id: 33,
    word: 'skirt',
    translation: 'юбка',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/skirt.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/skirt.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 34,
    word: 'pants',
    translation: 'брюки',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/pants.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/pants.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 35,
    word: 'blouse',
    translation: 'блузка',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/blouse.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/blouse.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 36,
    word: 'dress',
    translation: 'платье',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/dress.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/dress.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 37,
    word: 'boot',
    translation: 'ботинок',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/boot.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/boot.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 38,
    word: 'shirt',
    translation: 'рубашка',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/shirt.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/shirt.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 39,
    word: 'coat',
    translation: 'пальто',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/coat.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/coat.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
  {
    id: 40,
    word: 'shoe',
    translation: 'туфли',
    image: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/img/shoe.jpg',
    audioSrc: 'https://raw.githubusercontent.com/DenisAfa/assets-for-english-for-kids/main/audio/shoe.mp3',
    train: 0,
    game: 0,
    error: 0,
  },
];

export default cardsClothes;
